name = "SoleXplorer"
uuid = "5816ab97-8dbe-4a0a-b2fb-0334bd9876ed"
version = "0.1.0"
authors = ["Lorenzo BALBONI", "Michele GHIOTTI", "Federico MANZELLA", "Mauro MILELLA", "Giovanni PAGLIARINI", "Alberto PAPARELLA", "Riccardo PASINI", "Marco PERROTTA"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataTreatments = "1b3ff5f2-9b56-42a2-b38a-76a033f741ca"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Imbalance = "c709b415-507b-45b7-9a3d-1767c89fde68"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
MLJParticleSwarmOptimization = "17a086e9-ed03-4f30-ab88-8b63f0f6126c"
MLJXGBoostInterface = "54119dfa-1dab-4055-a167-80440f4f7a91"
ModalDecisionTrees = "e54bda2e-c571-11ec-9d64-0242ac120002"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SoleData = "123f1ae1-6307-4526-ab5b-aab3a92a2b8c"
SoleModels = "4249d9c7-3290-4ddd-961c-e1d3ec2467f8"
SolePostHoc = "cf1aa0c3-12c9-4ebe-9bdc-bd6c2ca79b72"
XGBoost = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"

[sources]
SolePostHoc = {rev = "devPaso", url = "https://github.com/aclai-lab/SolePostHoc.jl"}

[compat]
DataFrames = "1"
DataTreatments = "0.1"
DimensionalData = "0.29"
Imbalance = "0.1"
JLD2 = "0.6"
MLJ = "0.20, 0.21, 0.22"
MLJDecisionTreeInterface = "0.4"
MLJParticleSwarmOptimization = "0.1"
MLJXGBoostInterface = "0.3"
ModalDecisionTrees = "0.5"
Random = "1"
Reexport = "1"
SoleData = "0.16"
SoleModels = "0.10"
SolePostHoc = "0.1"
XGBoost = "2.5"
julia = "1"

[extras]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JLD2", "Test"]
